import type { Metadata } from "next";
import localFont from "next/font/local";
import { HeaderComponent } from "@/components/header";
import { LightDarkProvider } from "./theme/LightDarkProvider";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">

      <head>
        <title>NoteNectar</title>
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <LightDarkProvider>
          <HeaderComponent />
          {children}
        </LightDarkProvider>
      </body>
    </html>
  );
}
